// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file workloadapi.proto (syntax proto3)
/* eslint-disable */

import type { JsonObject, Message } from '@bufbuild/protobuf';
import type { GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';
import { file_google_protobuf_struct } from '@bufbuild/protobuf/wkt';

/**
 * Describes the file workloadapi.proto.
 */
export const file_workloadapi: GenFile /*@__PURE__*/ = fileDesc(
  'ChF3b3JrbG9hZGFwaS5wcm90byIRCg9YNTA5U1ZJRFJlcXVlc3QitgEKEFg1MDlTVklEUmVzcG9uc2USGAoFc3ZpZHMYASADKAsyCS5YNTA5U1ZJRBILCgNjcmwYAiADKAwSQgoRZmVkZXJhdGVkX2J1bmRsZXMYAyADKAsyJy5YNTA5U1ZJRFJlc3BvbnNlLkZlZGVyYXRlZEJ1bmRsZXNFbnRyeRo3ChVGZWRlcmF0ZWRCdW5kbGVzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgMOgI4ASJlCghYNTA5U1ZJRBIRCglzcGlmZmVfaWQYASABKAkSEQoJeDUwOV9zdmlkGAIgASgMEhUKDXg1MDlfc3ZpZF9rZXkYAyABKAwSDgoGYnVuZGxlGAQgASgMEgwKBGhpbnQYBSABKAkiFAoSWDUwOUJ1bmRsZXNSZXF1ZXN0IoYBChNYNTA5QnVuZGxlc1Jlc3BvbnNlEgsKA2NybBgBIAMoDBIyCgdidW5kbGVzGAIgAygLMiEuWDUwOUJ1bmRsZXNSZXNwb25zZS5CdW5kbGVzRW50cnkaLgoMQnVuZGxlc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoDDoCOAEiNQoOSldUU1ZJRFJlcXVlc3QSEAoIYXVkaWVuY2UYASADKAkSEQoJc3BpZmZlX2lkGAIgASgJIioKD0pXVFNWSURSZXNwb25zZRIXCgVzdmlkcxgBIAMoCzIILkpXVFNWSUQiOAoHSldUU1ZJRBIRCglzcGlmZmVfaWQYASABKAkSDAoEc3ZpZBgCIAEoCRIMCgRoaW50GAMgASgJIhMKEUpXVEJ1bmRsZXNSZXF1ZXN0IncKEkpXVEJ1bmRsZXNSZXNwb25zZRIxCgdidW5kbGVzGAEgAygLMiAuSldUQnVuZGxlc1Jlc3BvbnNlLkJ1bmRsZXNFbnRyeRouCgxCdW5kbGVzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgMOgI4ASI4ChZWYWxpZGF0ZUpXVFNWSURSZXF1ZXN0EhAKCGF1ZGllbmNlGAEgASgJEgwKBHN2aWQYAiABKAkiVQoXVmFsaWRhdGVKV1RTVklEUmVzcG9uc2USEQoJc3BpZmZlX2lkGAEgASgJEicKBmNsYWltcxgCIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QywwIKEVNwaWZmZVdvcmtsb2FkQVBJEjYKDUZldGNoWDUwOVNWSUQSEC5YNTA5U1ZJRFJlcXVlc3QaES5YNTA5U1ZJRFJlc3BvbnNlMAESPwoQRmV0Y2hYNTA5QnVuZGxlcxITLlg1MDlCdW5kbGVzUmVxdWVzdBoULlg1MDlCdW5kbGVzUmVzcG9uc2UwARIxCgxGZXRjaEpXVFNWSUQSDy5KV1RTVklEUmVxdWVzdBoQLkpXVFNWSURSZXNwb25zZRI8Cg9GZXRjaEpXVEJ1bmRsZXMSEi5KV1RCdW5kbGVzUmVxdWVzdBoTLkpXVEJ1bmRsZXNSZXNwb25zZTABEkQKD1ZhbGlkYXRlSldUU1ZJRBIXLlZhbGlkYXRlSldUU1ZJRFJlcXVlc3QaGC5WYWxpZGF0ZUpXVFNWSURSZXNwb25zZWIGcHJvdG8z',
  [file_google_protobuf_struct],
);

/**
 * The X509SVIDRequest message conveys parameters for requesting an X.509-SVID.
 * There are currently no request parameters.
 *
 * @generated from message X509SVIDRequest
 */
export type X509SVIDRequest = Message<'X509SVIDRequest'> & {};

/**
 * Describes the message X509SVIDRequest.
 * Use `create(X509SVIDRequestSchema)` to create a new message.
 */
export const X509SVIDRequestSchema: GenMessage<X509SVIDRequest> /*@__PURE__*/ = messageDesc(
  file_workloadapi,
  0,
);

/**
 * The X509SVIDResponse message carries X.509-SVIDs and related information,
 * including a set of global CRLs and a list of bundles the workload may use
 * for federating with foreign trust domains.
 *
 * @generated from message X509SVIDResponse
 */
export type X509SVIDResponse = Message<'X509SVIDResponse'> & {
  /**
   * Required. A list of X509SVID messages, each of which includes a single
   * X.509-SVID, its private key, and the bundle for the trust domain.
   *
   * @generated from field: repeated X509SVID svids = 1;
   */
  svids: X509SVID[];

  /**
   * Optional. ASN.1 DER encoded certificate revocation lists.
   *
   * @generated from field: repeated bytes crl = 2;
   */
  crl: Uint8Array[];

  /**
   * Optional. CA certificate bundles belonging to foreign trust domains that
   * the workload should trust, keyed by the SPIFFE ID of the foreign trust
   * domain. Bundles are ASN.1 DER encoded.
   *
   * @generated from field: map<string, bytes> federated_bundles = 3;
   */
  federatedBundles: { [key: string]: Uint8Array };
};

/**
 * Describes the message X509SVIDResponse.
 * Use `create(X509SVIDResponseSchema)` to create a new message.
 */
export const X509SVIDResponseSchema: GenMessage<X509SVIDResponse> /*@__PURE__*/ = messageDesc(
  file_workloadapi,
  1,
);

/**
 * The X509SVID message carries a single SVID and all associated information,
 * including the X.509 bundle for the trust domain.
 *
 * @generated from message X509SVID
 */
export type X509SVID = Message<'X509SVID'> & {
  /**
   * Required. The SPIFFE ID of the SVID in this entry
   *
   * @generated from field: string spiffe_id = 1;
   */
  spiffeId: string;

  /**
   * Required. ASN.1 DER encoded certificate chain. MAY include
   * intermediates, the leaf certificate (or SVID itself) MUST come first.
   *
   * @generated from field: bytes x509_svid = 2;
   */
  x509Svid: Uint8Array;

  /**
   * Required. ASN.1 DER encoded PKCS#8 private key. MUST be unencrypted.
   *
   * @generated from field: bytes x509_svid_key = 3;
   */
  x509SvidKey: Uint8Array;

  /**
   * Required. ASN.1 DER encoded X.509 bundle for the trust domain.
   *
   * @generated from field: bytes bundle = 4;
   */
  bundle: Uint8Array;

  /**
   * Optional. An operator-specified string used to provide guidance on how this
   * identity should be used by a workload when more than one SVID is returned.
   * For example, `internal` and `external` to indicate an SVID for internal or
   * external use, respectively.
   *
   * @generated from field: string hint = 5;
   */
  hint: string;
};

/**
 * Describes the message X509SVID.
 * Use `create(X509SVIDSchema)` to create a new message.
 */
export const X509SVIDSchema: GenMessage<X509SVID> /*@__PURE__*/ = messageDesc(file_workloadapi, 2);

/**
 * The X509BundlesRequest message conveys parameters for requesting X.509
 * bundles. There are currently no such parameters.
 *
 * @generated from message X509BundlesRequest
 */
export type X509BundlesRequest = Message<'X509BundlesRequest'> & {};

/**
 * Describes the message X509BundlesRequest.
 * Use `create(X509BundlesRequestSchema)` to create a new message.
 */
export const X509BundlesRequestSchema: GenMessage<X509BundlesRequest> /*@__PURE__*/ = messageDesc(
  file_workloadapi,
  3,
);

/**
 * The X509BundlesResponse message carries a set of global CRLs and a map of
 * trust bundles the workload should trust.
 *
 * @generated from message X509BundlesResponse
 */
export type X509BundlesResponse = Message<'X509BundlesResponse'> & {
  /**
   * Optional. ASN.1 DER encoded certificate revocation lists.
   *
   * @generated from field: repeated bytes crl = 1;
   */
  crl: Uint8Array[];

  /**
   * Required. CA certificate bundles belonging to trust domains that the
   * workload should trust, keyed by the SPIFFE ID of the trust domain.
   * Bundles are ASN.1 DER encoded.
   *
   * @generated from field: map<string, bytes> bundles = 2;
   */
  bundles: { [key: string]: Uint8Array };
};

/**
 * Describes the message X509BundlesResponse.
 * Use `create(X509BundlesResponseSchema)` to create a new message.
 */
export const X509BundlesResponseSchema: GenMessage<X509BundlesResponse> /*@__PURE__*/ = messageDesc(
  file_workloadapi,
  4,
);

/**
 * @generated from message JWTSVIDRequest
 */
export type JWTSVIDRequest = Message<'JWTSVIDRequest'> & {
  /**
   * Required. The audience(s) the workload intends to authenticate against.
   *
   * @generated from field: repeated string audience = 1;
   */
  audience: string[];

  /**
   * Optional. The requested SPIFFE ID for the JWT-SVID. If unset, all
   * JWT-SVIDs to which the workload is entitled are requested.
   *
   * @generated from field: string spiffe_id = 2;
   */
  spiffeId: string;
};

/**
 * Describes the message JWTSVIDRequest.
 * Use `create(JWTSVIDRequestSchema)` to create a new message.
 */
export const JWTSVIDRequestSchema: GenMessage<JWTSVIDRequest> /*@__PURE__*/ = messageDesc(
  file_workloadapi,
  5,
);

/**
 * The JWTSVIDResponse message conveys JWT-SVIDs.
 *
 * @generated from message JWTSVIDResponse
 */
export type JWTSVIDResponse = Message<'JWTSVIDResponse'> & {
  /**
   * Required. The list of returned JWT-SVIDs.
   *
   * @generated from field: repeated JWTSVID svids = 1;
   */
  svids: JWTSVID[];
};

/**
 * Describes the message JWTSVIDResponse.
 * Use `create(JWTSVIDResponseSchema)` to create a new message.
 */
export const JWTSVIDResponseSchema: GenMessage<JWTSVIDResponse> /*@__PURE__*/ = messageDesc(
  file_workloadapi,
  6,
);

/**
 * The JWTSVID message carries the JWT-SVID token and associated metadata.
 *
 * @generated from message JWTSVID
 */
export type JWTSVID = Message<'JWTSVID'> & {
  /**
   * Required. The SPIFFE ID of the JWT-SVID.
   *
   * @generated from field: string spiffe_id = 1;
   */
  spiffeId: string;

  /**
   * Required. Encoded JWT using JWS Compact Serialization.
   *
   * @generated from field: string svid = 2;
   */
  svid: string;

  /**
   * Optional. An operator-specified string used to provide guidance on how this
   * identity should be used by a workload when more than one SVID is returned.
   * For example, `internal` and `external` to indicate an SVID for internal or
   * external use, respectively.
   *
   * @generated from field: string hint = 3;
   */
  hint: string;
};

/**
 * Describes the message JWTSVID.
 * Use `create(JWTSVIDSchema)` to create a new message.
 */
export const JWTSVIDSchema: GenMessage<JWTSVID> /*@__PURE__*/ = messageDesc(file_workloadapi, 7);

/**
 * The JWTBundlesRequest message conveys parameters for requesting JWT bundles.
 * There are currently no such parameters.
 *
 * @generated from message JWTBundlesRequest
 */
export type JWTBundlesRequest = Message<'JWTBundlesRequest'> & {};

/**
 * Describes the message JWTBundlesRequest.
 * Use `create(JWTBundlesRequestSchema)` to create a new message.
 */
export const JWTBundlesRequestSchema: GenMessage<JWTBundlesRequest> /*@__PURE__*/ = messageDesc(
  file_workloadapi,
  8,
);

/**
 * The JWTBundlesResponse conveys JWT bundles.
 *
 * @generated from message JWTBundlesResponse
 */
export type JWTBundlesResponse = Message<'JWTBundlesResponse'> & {
  /**
   * Required. JWK encoded JWT bundles, keyed by the SPIFFE ID of the trust
   * domain.
   *
   * @generated from field: map<string, bytes> bundles = 1;
   */
  bundles: { [key: string]: Uint8Array };
};

/**
 * Describes the message JWTBundlesResponse.
 * Use `create(JWTBundlesResponseSchema)` to create a new message.
 */
export const JWTBundlesResponseSchema: GenMessage<JWTBundlesResponse> /*@__PURE__*/ = messageDesc(
  file_workloadapi,
  9,
);

/**
 * The ValidateJWTSVIDRequest message conveys request parameters for
 * JWT-SVID validation.
 *
 * @generated from message ValidateJWTSVIDRequest
 */
export type ValidateJWTSVIDRequest = Message<'ValidateJWTSVIDRequest'> & {
  /**
   * Required. The audience of the validating party. The JWT-SVID must
   * contain an audience claim which contains this value in order to
   * succesfully validate.
   *
   * @generated from field: string audience = 1;
   */
  audience: string;

  /**
   * Required. The JWT-SVID to validate, encoded using JWS Compact
   * Serialization.
   *
   * @generated from field: string svid = 2;
   */
  svid: string;
};

/**
 * Describes the message ValidateJWTSVIDRequest.
 * Use `create(ValidateJWTSVIDRequestSchema)` to create a new message.
 */
export const ValidateJWTSVIDRequestSchema: GenMessage<ValidateJWTSVIDRequest> /*@__PURE__*/ =
  messageDesc(file_workloadapi, 10);

/**
 * The ValidateJWTSVIDResponse message conveys the JWT-SVID validation results.
 *
 * @generated from message ValidateJWTSVIDResponse
 */
export type ValidateJWTSVIDResponse = Message<'ValidateJWTSVIDResponse'> & {
  /**
   * Required. The SPIFFE ID of the validated JWT-SVID.
   *
   * @generated from field: string spiffe_id = 1;
   */
  spiffeId: string;

  /**
   * Required. Claims contained within the payload of the validated JWT-SVID.
   * This includes both SPIFFE-required and non-required claims.
   *
   * @generated from field: google.protobuf.Struct claims = 2;
   */
  claims?: JsonObject | undefined;
};

/**
 * Describes the message ValidateJWTSVIDResponse.
 * Use `create(ValidateJWTSVIDResponseSchema)` to create a new message.
 */
export const ValidateJWTSVIDResponseSchema: GenMessage<ValidateJWTSVIDResponse> /*@__PURE__*/ =
  messageDesc(file_workloadapi, 11);

/**
 * ///////////////////////////////////////////////////////////////////////
 * X509-SVID Profile
 * ///////////////////////////////////////////////////////////////////////
 *
 * @generated from service SpiffeWorkloadAPI
 */
export const SpiffeWorkloadAPI: GenService<{
  /**
   * Fetch X.509-SVIDs for all SPIFFE identities the workload is entitled to,
   * as well as related information like trust bundles and CRLs. As this
   * information changes, subsequent messages will be streamed from the
   * server.
   *
   * @generated from rpc SpiffeWorkloadAPI.FetchX509SVID
   */
  fetchX509SVID: {
    methodKind: 'server_streaming';
    input: typeof X509SVIDRequestSchema;
    output: typeof X509SVIDResponseSchema;
  };
  /**
   * Fetch trust bundles and CRLs. Useful for clients that only need to
   * validate SVIDs without obtaining an SVID for themself. As this
   * information changes, subsequent messages will be streamed from the
   * server.
   *
   * @generated from rpc SpiffeWorkloadAPI.FetchX509Bundles
   */
  fetchX509Bundles: {
    methodKind: 'server_streaming';
    input: typeof X509BundlesRequestSchema;
    output: typeof X509BundlesResponseSchema;
  };
  /**
   * Fetch JWT-SVIDs for all SPIFFE identities the workload is entitled to,
   * for the requested audience. If an optional SPIFFE ID is requested, only
   * the JWT-SVID for that SPIFFE ID is returned.
   *
   * @generated from rpc SpiffeWorkloadAPI.FetchJWTSVID
   */
  fetchJWTSVID: {
    methodKind: 'unary';
    input: typeof JWTSVIDRequestSchema;
    output: typeof JWTSVIDResponseSchema;
  };
  /**
   * Fetches the JWT bundles, formatted as JWKS documents, keyed by the
   * SPIFFE ID of the trust domain. As this information changes, subsequent
   * messages will be streamed from the server.
   *
   * @generated from rpc SpiffeWorkloadAPI.FetchJWTBundles
   */
  fetchJWTBundles: {
    methodKind: 'server_streaming';
    input: typeof JWTBundlesRequestSchema;
    output: typeof JWTBundlesResponseSchema;
  };
  /**
   * Validates a JWT-SVID against the requested audience. Returns the SPIFFE
   * ID of the JWT-SVID and JWT claims.
   *
   * @generated from rpc SpiffeWorkloadAPI.ValidateJWTSVID
   */
  validateJWTSVID: {
    methodKind: 'unary';
    input: typeof ValidateJWTSVIDRequestSchema;
    output: typeof ValidateJWTSVIDResponseSchema;
  };
}> /*@__PURE__*/ = serviceDesc(file_workloadapi, 0);
