coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: cache
      paths:
        - packages/cache/src
    - name: config
      paths:
        - packages/config/src
    - name: prelude
      paths:
        - packages/prelude/src
    - name: spiffe
      paths:
        - packages/spiffe/src

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: cache
      name: cache
      paths:
        - packages/cache/src
    - component_id: config
      name: config
      paths:
        - packages/config/src
    - component_id: prelude
      name: prelude
      paths:
        - packages/prelude/src
    - component_id: spiffe
      name: spiffe
      paths:
        - packages/spiffe/src

comment:
  layout: 'condensed_header, flags, components, condensed_files, condensed_footer'
  require_changes: false
